name: CI/CD Pipeline

on:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    security:
        name: Snyk Security Scan
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
            - run: npm ci
            - name: Snyk Scan
              uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.GH_WORKFLOW_SNYK_TOKEN }}
              with:
                  args: --sarif-file-output=snyk.sarif
            - name: Upload Snyk scan results to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v4
              with:
                  sarif_file: snyk.sarif

    test:
        name: Test, Lint, Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
            - run: npm ci

            - name: Check code formatting
              run: npm run format:check

            - name: Lint code
              run: npm run lint

            - name: Type check
              run: npm run type:check

            - name: Run tests
              run: npm test

    release:
        name: version bump
        needs: [test, security]
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
        steps:
            - name: Set up Release Please
              id: release
              uses: GoogleCloudPlatform/release-please-action@v4
              with:
                  token: ${{ secrets.GH_WORKFLOW_TOKEN_RELEASE }}
                  release-type: node
                  bump-minor-pre-major: true
                  versioning-strategy: default

            - name: Merge release PR
              if: ${{ steps.release.outputs.pr != '' }}
              uses: peter-evans/enable-pull-request-automerge@v3
              with:
                  token: ${{ secrets.GH_WORKFLOW_TOKEN_RELEASE }}
                  pull-request-number: ${{ fromJson(steps.release.outputs.pr).number }}
                  merge-method: squash

    publish-npm:
        name: Publish to NPM
        needs: release
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && needs.release.outputs.release_created
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org/
                  cache: 'npm'
            - run: npm ci
            - run: npm publish  --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GH_WORKFLOW_TOKEN_NPM}}
